name: github_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.0.6

dependencies:
  dio: ^5.3.3
  freezed_annotation: ^2.4.1
  pedantic_mono: ^1.24.0+1
  retrofit: ">=4.0.0 <5.0.0"
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ">=2.3.0 <4.0.0"
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  retrofit_generator: ">=8.0.3"
