# https://github.blog/changelog/2022-04-05-pub-beta-support-for-dependabot-version-updates/
version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Asia/Tokyo"
      time: "09:00"
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Asia/Tokyo"
      time: "09:00"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Asia/Tokyo"
      time: "09:00"
  - package-ecosystem: "pub"
    directory: "/packages/app"
    schedule:
      interval: "daily"
      timezone: "Asia/Tokyo"
      time: "09:00"
