name: dart_frog_github_repository_search
description: Dart Frog Sample Application
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.1.3

dev_dependencies:
  melos: ^4.0.0
dependencies:
  pedantic_mono: ^1.24.0+1
