name: bff_api_types
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.1.3

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  pedantic_mono: ^1.24.0+1

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
