name: bff
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bff_api_types:
    git:
      url: git@github.com:YumNumm/dart-frog-github-repository-search.git
      path: packages/bff_api_types
  dart_frog: ^1.0.0
  github_api:
    git:
      url: git@github.com:YumNumm/dart-frog-github-repository-search.git
      path: packages/github_api

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
