name: github_repository_search
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ^3.1.0

dependencies:
  bff_api_types:
    git:
      url: git@github.com:YumNumm/dart-frog-github-repository-search.git
      path: packages/bff_api_types
  collection: ^1.17.2

  cupertino_icons: ^1.0.6
  device_info_plus: ^9.1.0
  device_preview: ^1.1.0
  dio: ^5.3.3
  dio_http2_adapter: ^2.3.1+1
  dynamic_color: ^1.6.8
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.5
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.4.1
  go_router: ^12.0.1
  hooks_riverpod: ^2.4.5
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  lottie: ^2.7.0
  retrofit: ^4.0.3
  riverpod_annotation: ^2.3.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  slang: ^3.25.0
  slang_flutter: ^3.25.0
  substring_highlight: ^1.0.33
  url_launcher: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  go_router_builder: ^2.3.4
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1
  pedantic_mono: ^1.24.0
  retrofit_generator: ^8.0.3
  riverpod_generator: ^2.3.9
  slang_build_runner: ^3.25.0

flutter:
  uses-material-design: true

  assets:
    - assets/
