name: deploy API
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: srv2-osaka
    defaults:
      run:
        working-directory: /opt/dart-frog-github-repository-search
    steps:
      - run: |
          git pull
          docker compose build
          docker compose up -d
          docker compose ps