name: Flutter Unit Test

#発火条件
on:
  #ソースをmainブランチにプッシュする時
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  test:
    #ビルド環境
    runs-on: ubuntu-latest
    # タイムアウト時間を設定
    timeout-minutes: 45

    steps:
      #リポジトリからソースをダンロード
      - uses: actions/checkout@v2

      #JAVA環境構築
      - name: Setup Java 17
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "17"
          cache: "gradle"

      - name: Add Homebrew to PATH
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

      - name: Install fvm
        run: |
          brew tap leoafarias/fvm
          brew install fvm

      - name: Setup flutter
        run: fvm install

      - name: Flutter version
        run: fvm flutter --version

      - name: Flutter dependencies install
        run: fvm flutter pub get

      - name: Generate codes with build_runner
        run: fvm flutter pub run build_runner build --delete-conflicting-outputs

      - name: Accept Android License
        run: yes | fvm flutter doctor --android-licenses

      - name: Flutter Test
        run: fvm flutter test --no-test-assets --coverage --coverage-path=~/coverage/lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ~/coverage/lcov.info
          flags: UnitTest
          token: ${{ secrets.CODECOV_TOKEN }}
          