name: Flutter Unit Test

#発火条件
on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      # https://github.com/kuhnroyal/flutter-fvm-config-action
      - name: Fetch flutter config
        uses: kuhnroyal/flutter-fvm-config-action@v1

      # https://github.com/subosito/flutter-action
      - name: Set up flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          cache-key: ${{ env.FLUTTER_VERSION }}-${{ env.FLUTTER_CHANNEL }}

      - name: Flutter version
        run: flutter --version

      - name: Flutter dependencies install
        run: flutter pub get

      - name: Generate codes with build_runner
        run: flutter pub run build_runner build -d

      - name: Generate translations
        run: flutter pub run slang

      - name: Accept Android License
        run: yes | flutter doctor --android-licenses

      - name: Flutter Test
        run: flutter test --no-test-assets --coverage --coverage-path=~/coverage/lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ~/coverage/lcov.info
          flags: UnitTest
          token: ${{ secrets.CODECOV_TOKEN }}
